#!/usr/bin/env python3
"""Write .po files with translations for all target languages."""

import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
DOMAIN = "blooms-in-gnome"
POT = HERE / "locale" / f"{DOMAIN}.pot"

STRINGS = [
    "Current config:",
    "(not set)",
    "(defaults)",
    "(stored in keyring)",
    "Config file:",
    "CLI:",
    "nsec saved to keyring",
    "npub set to {npub}",
    "server added: {url}",
    "relay added: {url}",
    "Blooms in Gnome \u2014 Blossom FUSE mount",
    "Mount point (default: ~/Blossom)",
    "Show current configuration",
    "Run FUSE mount in foreground",
    "Start tray icon (starts FUSE mount automatically)",
    "Store nsec in keyring",
    "Set public key",
    "Add a Blossom server",
    "Add a Nostr relay",
    "server: {url}\n",
    "pubkey: {key}\n",
    "blobs: {count}\n",
    "named: {count}\n",
    "Starting\u2026",
    "Not configured",
    "Connected \u2014 {count} blob",
    "Connected \u2014 {count} blobs",
    "Disconnected",
    "Open Folder",
    "Upload File\u2026",
    "Config",
    "Quit",
    "Select file to upload to Blossom",
    "Cancel",
    "Upload",
    "Configure keys and servers first",
    "Uploaded: {hash}\u2026",
    "Upload failed: {error}",
    "Blooms in Gnome",
]

TRANSLATIONS = {
    "zh_CN": [
        "当前配置：", "（未设置）", "（默认）", "（存储在钥匙环中）",
        "配置文件：", "命令行：", "nsec 已保存到钥匙环",
        "npub 设置为 {npub}", "服务器已添加：{url}", "中继已添加：{url}",
        "Blooms in Gnome — Blossom FUSE 挂载",
        "挂载点（默认：~/Blossom）", "显示当前配置",
        "在前台运行 FUSE 挂载",
        "启动托盘图标（自动启动 FUSE 挂载）",
        "将 nsec 存储在钥匙环中", "设置公钥", "添加 Blossom 服务器",
        "添加 Nostr 中继", "服务器：{url}\n", "公钥：{key}\n",
        "对象数：{count}\n", "已命名：{count}\n", "启动中…", "未配置",
        "已连接 — {count} 个对象", "已连接 — {count} 个对象", "已断开",
        "打开文件夹", "上传文件…", "配置", "退出",
        "选择要上传到 Blossom 的文件", "取消", "上传",
        "请先配置密钥和服务器", "已上传：{hash}…",
        "上传失败：{error}", "Blooms in Gnome",
    ],
    "zh_TW": [
        "目前配置：", "（未設定）", "（預設）", "（儲存在鑰匙圈中）",
        "設定檔：", "命令列：", "nsec 已儲存到鑰匙圈",
        "npub 設定為 {npub}", "伺服器已新增：{url}", "中繼已新增：{url}",
        "Blooms in Gnome — Blossom FUSE 掛載",
        "掛載點（預設：~/Blossom）", "顯示目前設定",
        "在前景執行 FUSE 掛載",
        "啟動系統托盤圖示（自動啟動 FUSE 掛載）",
        "將 nsec 儲存在鑰匙圈中", "設定公鑰", "新增 Blossom 伺服器",
        "新增 Nostr 中繼", "伺服器：{url}\n", "公鑰：{key}\n",
        "物件數：{count}\n", "已命名：{count}\n", "啟動中…", "未設定",
        "已連線 — {count} 個物件", "已連線 — {count} 個物件", "已中斷",
        "開啟資料夾", "上傳檔案…", "設定", "退出",
        "選擇要上傳到 Blossom 的檔案", "取消", "上傳",
        "請先設定金鑰和伺服器", "已上傳：{hash}…",
        "上傳失敗：{error}", "Blooms in Gnome",
    ],
    "es": [
        "Configuración actual:", "(sin establecer)", "(predeterminados)",
        "(almacenado en el llavero)", "Archivo de configuración:", "CLI:",
        "nsec guardado en el llavero", "npub establecido en {npub}",
        "servidor añadido: {url}", "relé añadido: {url}",
        "Blooms in Gnome — Montaje FUSE de Blossom",
        "Punto de montaje (predeterminado: ~/Blossom)",
        "Mostrar configuración actual",
        "Ejecutar montaje FUSE en primer plano",
        "Iniciar icono de bandeja (inicia montaje FUSE automáticamente)",
        "Guardar nsec en el llavero", "Establecer clave pública",
        "Añadir un servidor Blossom", "Añadir un relé Nostr",
        "servidor: {url}\n", "clave pública: {key}\n", "blobs: {count}\n",
        "nombrados: {count}\n", "Iniciando…", "No configurado",
        "Conectado — {count} blob", "Conectado — {count} blobs",
        "Desconectado", "Abrir carpeta", "Subir archivo…",
        "Configuración", "Salir", "Seleccionar archivo para subir a Blossom",
        "Cancelar", "Subir", "Configure claves y servidores primero",
        "Subido: {hash}…", "Error al subir: {error}", "Blooms in Gnome",
    ],
    "hi": [
        "वर्तमान कॉन्फ़िगरेशन:", "(सेट नहीं है)", "(डिफ़ॉल्ट)",
        "(कीरिंग में संग्रहीत)", "कॉन्फ़िग फ़ाइल:", "CLI:",
        "nsec कीरिंग में सहेजा गया", "npub {npub} पर सेट किया गया",
        "सर्वर जोड़ा गया: {url}", "रिले जोड़ा गया: {url}",
        "Blooms in Gnome — Blossom FUSE माउंट",
        "माउंट पॉइंट (डिफ़ॉल्ट: ~/Blossom)",
        "वर्तमान कॉन्फ़िगरेशन दिखाएँ",
        "FUSE माउंट को अग्रभूमि में चलाएँ",
        "ट्रे आइकन शुरू करें (स्वचालित रूप से FUSE माउंट शुरू करता है)",
        "कीरिंग में nsec स्टोर करें", "सार्वजनिक कुंजी सेट करें",
        "Blossom सर्वर जोड़ें", "Nostr रिले जोड़ें",
        "सर्वर: {url}\n", "सार्वजनिक कुंजी: {key}\n", "ब्लॉब: {count}\n",
        "नामांकित: {count}\n", "शुरू हो रहा है…", "कॉन्फ़िगर नहीं किया गया",
        "कनेक्टेड — {count} ब्लॉब", "कनेक्टेड — {count} ब्लॉब",
        "डिस्कनेक्टेड", "फ़ोल्डर खोलें", "फ़ाइल अपलोड करें…",
        "कॉन्फ़िग", "बाहर निकलें",
        "Blossom पर अपलोड करने के लिए फ़ाइल चुनें",
        "रद्द करें", "अपलोड करें",
        "पहले कुंजियाँ और सर्वर कॉन्फ़िगर करें",
        "अपलोड किया गया: {hash}…",
        "अपलोड विफल: {error}", "Blooms in Gnome",
    ],
    "ar": [
        "الإعدادات الحالية:", "(غير مضبوط)", "(الافتراضي)",
        "(مخزن في سلسلة المفاتيح)", "ملف الإعدادات:", "سطر الأوامر:",
        "تم حفظ nsec في سلسلة المفاتيح", "تم تعيين npub إلى {npub}",
        "تمت إضافة الخادم: {url}", "تمت إضافة المرحل: {url}",
        "Blooms in Gnome — تثبيت FUSE لـ Blossom",
        "نقطة التثبيت (الافتراضي: ~/Blossom)", "عرض الإعدادات الحالية",
        "تشغيل تثبيت FUSE في المقدمة",
        "بدء أيقونة الدرج (يبدأ تثبيت FUSE تلقائياً)",
        "تخزين nsec في سلسلة المفاتيح", "تعيين المفتاح العام",
        "إضافة خادم Blossom", "إضافة مرحل Nostr",
        "الخادم: {url}\n", "المفتاح العام: {key}\n", "الملفات: {count}\n",
        "المسماة: {count}\n", "جارٍ البدء…", "غير مهيأ",
        "متصل — {count} ملف", "متصل — {count} ملفات",
        "غير متصل", "فتح المجلد", "رفع ملف…",
        "الإعدادات", "خروج", "اختر ملفاً لرفعه إلى Blossom",
        "إلغاء", "رفع", "قم بتكوين المفاتيح والخوادم أولاً",
        "تم الرفع: {hash}…", "فشل الرفع: {error}", "Blooms in Gnome",
    ],
    "pt_BR": [
        "Configuração atual:", "(não definido)", "(padrões)",
        "(armazenado no chaveiro)", "Arquivo de configuração:", "CLI:",
        "nsec salvo no chaveiro", "npub definido como {npub}",
        "servidor adicionado: {url}", "relé adicionado: {url}",
        "Blooms in Gnome — Montagem FUSE do Blossom",
        "Ponto de montagem (padrão: ~/Blossom)",
        "Mostrar configuração atual",
        "Executar montagem FUSE em primeiro plano",
        "Iniciar ícone da bandeja (inicia montagem FUSE automaticamente)",
        "Armazenar nsec no chaveiro", "Definir chave pública",
        "Adicionar um servidor Blossom", "Adicionar um relé Nostr",
        "servidor: {url}\n", "chave pública: {key}\n", "blobs: {count}\n",
        "nomeados: {count}\n", "Iniciando…", "Não configurado",
        "Conectado — {count} blob", "Conectado — {count} blobs",
        "Desconectado", "Abrir pasta", "Enviar arquivo…",
        "Configuração", "Sair", "Selecionar arquivo para enviar ao Blossom",
        "Cancelar", "Enviar", "Configure chaves e servidores primeiro",
        "Enviado: {hash}…", "Falha ao enviar: {error}", "Blooms in Gnome",
    ],
    "bn": [
        "বর্তমান কনফিগারেশন:", "(সেট করা হয়নি)", "(ডিফল্ট)",
        "(কিরিংয়ে সংরক্ষিত)", "কনফিগ ফাইল:", "CLI:",
        "nsec কিরিংয়ে সংরক্ষিত হয়েছে", "npub {npub} এ সেট করা হয়েছে",
        "সার্ভার যোগ করা হয়েছে: {url}", "রিলে যোগ করা হয়েছে: {url}",
        "Blooms in Gnome — Blossom FUSE মাউন্ট",
        "মাউন্ট পয়েন্ট (ডিফল্ট: ~/Blossom)", "বর্তমান কনফিগারেশন দেখান",
        "FUSE মাউন্ট foreground এ চালান",
        "ট্রে আইকন শুরু করুন (স্বয়ংক্রিয়ভাবে FUSE মাউন্ট শুরু করে)",
        "কিরিংয়ে nsec সংরক্ষণ করুন", "পাবলিক কী সেট করুন",
        "Blossom সার্ভার যোগ করুন", "Nostr রিলে যোগ করুন",
        "সার্ভার: {url}\n", "পাবলিক কী: {key}\n", "ব্লব: {count}\n",
        "নামকরণ: {count}\n", "শুরু হচ্ছে…", "কনফিগার করা হয়নি",
        "সংযুক্ত — {count} ব্লব", "সংযুক্ত — {count} ব্লব",
        "সংযোগ বিচ্ছিন্ন", "ফোল্ডার খুলুন", "ফাইল আপলোড করুন…",
        "কনফিগ", "প্রস্থান", "Blossom এ আপলোড করার জন্য ফাইল নির্বাচন করুন",
        "বাতিল", "আপলোড", "প্রথমে কী এবং সার্ভার কনফিগার করুন",
        "আপলোড করা হয়েছে: {hash}…",
        "আপলোড ব্যর্থ: {error}", "Blooms in Gnome",
    ],
    "ru": [
        "Текущая конфигурация:", "(не задано)", "(по умолчанию)",
        "(хранится в связке ключей)", "Файл конфигурации:", "CLI:",
        "nsec сохранён в связке ключей", "npub установлен в {npub}",
        "сервер добавлен: {url}", "реле добавлено: {url}",
        "Blooms in Gnome — Монтирование Blossom FUSE",
        "Точка монтирования (по умолчанию: ~/Blossom)",
        "Показать текущую конфигурацию",
        "Запустить монтирование FUSE на переднем плане",
        "Запустить значок в трее (автоматически запускает FUSE)",
        "Сохранить nsec в связке ключей", "Установить открытый ключ",
        "Добавить сервер Blossom", "Добавить реле Nostr",
        "сервер: {url}\n", "открытый ключ: {key}\n", "блобов: {count}\n",
        "именованных: {count}\n", "Запуск…", "Не настроено",
        "Подключено — {count} блоб", "Подключено — {count} блобов",
        "Отключено", "Открыть папку", "Загрузить файл…",
        "Настройки", "Выйти", "Выберите файл для загрузки в Blossom",
        "Отмена", "Загрузить", "Сначала настройте ключи и серверы",
        "Загружено: {hash}…", "Ошибка загрузки: {error}", "Blooms in Gnome",
    ],
    "ja": [
        "現在の設定：", "（未設定）", "（デフォルト）", "（キーリングに保存）",
        "設定ファイル：", "CLI：", "nsec をキーリングに保存しました",
        "npub を {npub} に設定しました", "サーバーを追加しました：{url}",
        "リレーを追加しました：{url}",
        "Blooms in Gnome — Blossom FUSE マウント",
        "マウントポイント（デフォルト：~/Blossom）", "現在の設定を表示",
        "FUSE マウントをフォアグラウンドで実行",
        "トレイアイコンを起動（自動的に FUSE マウントを開始）",
        "キーリングに nsec を保存", "公開鍵を設定",
        "Blossom サーバーを追加", "Nostr リレーを追加",
        "サーバー：{url}\n", "公開鍵：{key}\n", "ブロブ数：{count}\n",
        "名前付き：{count}\n", "起動中…", "未設定",
        "接続済み — {count} ブロブ", "接続済み — {count} ブロブ",
        "切断されました", "フォルダを開く", "ファイルをアップロード…",
        "設定", "終了", "Blossom にアップロードするファイルを選択",
        "キャンセル", "アップロード",
        "最初に鍵とサーバーを設定してください",
        "アップロード完了：{hash}…",
        "アップロード失敗：{error}", "Blooms in Gnome",
    ],
    "de": [
        "Aktuelle Konfiguration:", "(nicht gesetzt)", "(Standard)",
        "(im Schlüsselbund gespeichert)", "Konfigurationsdatei:", "CLI:",
        "nsec im Schlüsselbund gespeichert", "npub auf {npub} gesetzt",
        "Server hinzugefügt: {url}", "Relay hinzugefügt: {url}",
        "Blooms in Gnome — Blossom FUSE-Mount",
        "Mount-Punkt (Standard: ~/Blossom)", "Aktuelle Konfiguration anzeigen",
        "FUSE-Mount im Vordergrund ausführen",
        "Tray-Symbol starten (startet FUSE-Mount automatisch)",
        "nsec im Schlüsselbund speichern", "Öffentlichen Schlüssel setzen",
        "Blossom-Server hinzufügen", "Nostr-Relay hinzufügen",
        "Server: {url}\n", "Öffentlicher Schlüssel: {key}\n",
        "Blobs: {count}\n", "Benannte: {count}\n", "Starte…",
        "Nicht konfiguriert", "Verbunden — {count} Blob",
        "Verbunden — {count} Blobs", "Getrennt", "Ordner öffnen",
        "Datei hochladen…", "Konfiguration", "Beenden",
        "Datei zum Hochladen zu Blossom auswählen",
        "Abbrechen", "Hochladen",
        "Schlüssel und Server zuerst konfigurieren",
        "Hochgeladen: {hash}…", "Hochladen fehlgeschlagen: {error}",
        "Blooms in Gnome",
    ],
    "it": [
        "Configurazione corrente:", "(non impostato)", "(predefiniti)",
        "(archiviato nel portachiavi)", "File di configurazione:", "CLI:",
        "nsec salvato nel portachiavi", "npub impostato a {npub}",
        "server aggiunto: {url}", "relè aggiunto: {url}",
        "Blooms in Gnome — Montaggio FUSE Blossom",
        "Punto di montaggio (predefinito: ~/Blossom)",
        "Mostra configurazione corrente",
        "Esegui montaggio FUSE in primo piano",
        "Avvia icona della bandiera (avvia montaggio FUSE automaticamente)",
        "Salva nsec nel portachiavi", "Imposta chiave pubblica",
        "Aggiungi un server Blossom", "Aggiungi un relè Nostr",
        "server: {url}\n", "chiave pubblica: {key}\n", "blob: {count}\n",
        "denominati: {count}\n", "Avvio…", "Non configurato",
        "Connesso — {count} blob", "Connesso — {count} blob",
        "Disconnesso", "Apri cartella", "Carica file…",
        "Configurazione", "Esci", "Seleziona file da caricare su Blossom",
        "Annulla", "Carica", "Configura prima chiavi e server",
        "Caricato: {hash}…", "Caricamento fallito: {error}", "Blooms in Gnome",
    ],
    "ko": [
        "현재 설정:", "(설정되지 않음)", "(기본값)",
        "(키링에 저장됨)", "설정 파일:", "CLI:",
        "nsec가 키링에 저장되었습니다", "npub이 {npub}(으)로 설정되었습니다",
        "서버가 추가되었습니다: {url}", "릴레이가 추가되었습니다: {url}",
        "Blooms in Gnome — Blossom FUSE 마운트",
        "마운트 지점 (기본값: ~/Blossom)", "현재 설정 보기",
        "FUSE 마운트를 포그라운드에서 실행",
        "트레이 아이콘 시작 (자동으로 FUSE 마운트 시작)",
        "키링에 nsec 저장", "공개 키 설정",
        "Blossom 서버 추가", "Nostr 릴레이 추가",
        "서버: {url}\n", "공개 키: {key}\n", "블롭: {count}\n",
        "이름 지정: {count}\n", "시작 중…", "설정되지 않음",
        "연결됨 — {count} 블롭", "연결됨 — {count} 블롭",
        "연결 끊김", "폴더 열기", "파일 업로드…",
        "설정", "종료", "Blossom에 업로드할 파일 선택",
        "취소", "업로드", "먼저 키와 서버를 설정하세요",
        "업로드됨: {hash}…", "업로드 실패: {error}", "Blooms in Gnome",
    ],
    "tr": [
        "Mevcut yapılandırma:", "(ayarlanmamış)", "(varsayılanlar)",
        "(anahtarlıkta saklanıyor)", "Yapılandırma dosyası:", "CLI:",
        "nsec anahtarlığa kaydedildi", "npub {npub} olarak ayarlandı",
        "sunucu eklendi: {url}", "röle eklendi: {url}",
        "Blooms in Gnome — Blossom FUSE bağlama",
        "Bağlama noktası (varsayılan: ~/Blossom)",
        "Mevcut yapılandırmayı göster",
        "FUSE bağlamayı ön planda çalıştır",
        "Tepsi simgesini başlat (otomatik olarak FUSE bağlamayı başlatır)",
        "nsec'i anahtarlıkta sakla", "Açık anahtarı ayarla",
        "Blossom sunucusu ekle", "Nostr rölesi ekle",
        "sunucu: {url}\n", "açık anahtar: {key}\n", "blob: {count}\n",
        "adlandırılmış: {count}\n", "Başlatılıyor…", "Yapılandırılmamış",
        "Bağlı — {count} blob", "Bağlı — {count} blob",
        "Bağlantı kesildi", "Klasörü aç", "Dosya yükle…",
        "Yapılandırma", "Çıkış", "Blossom'a yüklenecek dosyayı seçin",
        "İptal", "Yükle", "Önce anahtarları ve sunucuları yapılandırın",
        "Yüklendi: {hash}…", "Yükleme başarısız: {error}", "Blooms in Gnome",
    ],
    "vi": [
        "Cấu hình hiện tại:", "(chưa đặt)", "(mặc định)",
        "(được lưu trong chùm khóa)", "Tệp cấu hình:", "CLI:",
        "nsec đã được lưu vào chùm khóa", "npub đã được đặt thành {npub}",
        "máy chủ đã được thêm: {url}", "rơ-le đã được thêm: {url}",
        "Blooms in Gnome — Gắn kết FUSE Blossom",
        "Điểm gắn kết (mặc định: ~/Blossom)", "Hiển thị cấu hình hiện tại",
        "Chạy gắn kết FUSE ở nền trước",
        "Khởi động biểu tượng khay (tự động khởi động gắn kết FUSE)",
        "Lưu nsec vào chùm khóa", "Đặt khóa công khai",
        "Thêm máy chủ Blossom", "Thêm rơ-le Nostr",
        "máy chủ: {url}\n", "khóa công khai: {key}\n", "blob: {count}\n",
        "đã đặt tên: {count}\n", "Đang khởi động…", "Chưa được cấu hình",
        "Đã kết nối — {count} blob", "Đã kết nối — {count} blob",
        "Đã ngắt kết nối", "Mở thư mục", "Tải tệp lên…",
        "Cấu hình", "Thoát", "Chọn tệp để tải lên Blossom",
        "Hủy", "Tải lên",
        "Vui lòng cấu hình khóa và máy chủ trước",
        "Đã tải lên: {hash}…", "Tải lên thất bại: {error}", "Blooms in Gnome",
    ],
    "pl": [
        "Bieżąca konfiguracja:", "(nie ustawiono)", "(domyślne)",
        "(przechowywane w pęku kluczy)", "Plik konfiguracyjny:", "CLI:",
        "nsec zapisany w pęku kluczy", "npub ustawiony na {npub}",
        "serwer dodany: {url}", "przekaźnik dodany: {url}",
        "Blooms in Gnome — Montowanie FUSE Blossom",
        "Punkt montowania (domyślnie: ~/Blossom)",
        "Pokaż bieżącą konfigurację",
        "Uruchom montowanie FUSE na pierwszym planie",
        "Uruchom ikonę zasobnika (automatycznie uruchamia FUSE)",
        "Zapisz nsec w pęku kluczy", "Ustaw klucz publiczny",
        "Dodaj serwer Blossom", "Dodaj przekaźnik Nostr",
        "serwer: {url}\n", "klucz publiczny: {key}\n", "blob: {count}\n",
        "nazwane: {count}\n", "Uruchamianie…", "Nieskonfigurowane",
        "Połączono — {count} blob", "Połączono — {count} bloby",
        "Rozłączono", "Otwórz folder", "Prześlij plik…",
        "Konfiguracja", "Wyjdź", "Wybierz plik do przesłania do Blossom",
        "Anuluj", "Prześlij", "Najpierw skonfiguruj klucze i serwery",
        "Przesłano: {hash}…", "Błąd przesyłania: {error}", "Blooms in Gnome",
    ],
}


def write_po(lang: str, translations: list[str]):
    po_path = HERE / "locale" / lang / "LC_MESSAGES" / f"{DOMAIN}.po"
    po_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f'# Translations for {DOMAIN} - {lang}',
        f'# Copyright (C) Blooms in Gnome contributors',
        f'# This file is distributed under the same license as the project.',
        f'#',
        f'msgid ""',
        f'msgstr ""',
        f'"Language: {lang}\\n"',
        f'"MIME-Version: 1.0\\n"',
        f'"Content-Type: text/plain; charset=UTF-8\\n"',
        f'"Content-Transfer-Encoding: 8bit\\n"',
        '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"',
        "",
    ]

    for msgid, msgstr in zip(STRINGS, translations):
        escaped_msgid = msgid.replace('"', '\\"')
        escaped_msgstr = msgstr.replace('"', '\\"')
        lines.append(f'msgid "{escaped_msgid}"')
        lines.append(f'msgstr "{escaped_msgstr}"')
        lines.append("")

    po_path.write_text("\n".join(lines) + "\n")
    print(f"  {lang}: {len(translations)} strings written")


def compile_po(lang: str):
    subprocess.run(
        ["pybabel", "compile",
         "--directory", str(HERE / "locale"),
         "--domain", DOMAIN,
         "--locale", lang],
        capture_output=True,
    )


def main():
    for lang, translations in TRANSLATIONS.items():
        assert len(translations) == len(STRINGS), \
            f"{lang}: expected {len(STRINGS)} strings, got {len(translations)}"
        write_po(lang, translations)

    print()
    print("Compiling...")
    for lang in TRANSLATIONS:
        compile_po(lang)
        print(f"  {lang}: compiled")

    print()
    print(f"Done! {len(TRANSLATIONS)} languages added.")


if __name__ == "__main__":
    main()
